<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-08-17T17:09:06Z" name="Invest Cloud Test Suite" finished-at="2020-08-17T17:09:30Z" duration-ms="23987">
    <groups>
      <group name="cucumber">
        <method signature="TestRunner.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.svb.qa.MyRunner.TestRunner@606e4010]" name="feature" class="com.svb.qa.MyRunner.TestRunner"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2020-08-17T17:09:06Z" name="Test Invest Cloud" finished-at="2020-08-17T17:09:30Z" duration-ms="23987">
      <class name="com.svb.qa.MyRunner.TestRunner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:com.svb.qa.MyRunner.TestRunner@606e4010]" started-at="2020-08-17T10:09:06Z" name="setUpClass" finished-at="2020-08-17T10:09:07Z" duration-ms="207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.svb.qa.MyRunner.TestRunner@606e4010]" started-at="2020-08-17T10:09:07Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2020-08-17T10:09:30Z" duration-ms="23554" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test Login Functionality]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.NullPointerException
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at com.svb.qa.MyRunner.TestRunner.feature(TestRunner.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy25.sendKeys(Unknown Source)
	at com.svb.qa.pages.LoginPage.enterUserName(LoginPage.java:31)
	at stepDefinitions.LoginPF.user_enter_username_and_password(LoginPF.java:56)
	at âœ½.When user enter username and password(Login.feature:9)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method is-config="true" signature="teatDownClass()[pri:0, instance:com.svb.qa.MyRunner.TestRunner@606e4010]" started-at="2020-08-17T10:09:30Z" name="teatDownClass" finished-at="2020-08-17T10:09:30Z" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teatDownClass -->
      </class> <!-- com.svb.qa.MyRunner.TestRunner -->
    </test> <!-- Test Invest Cloud -->
  </suite> <!-- Invest Cloud Test Suite -->
</testng-results>
